name: Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Add SSH Key
      run: |
        mkdir -p ${HOME}/.ssh
        echo "${{secrets.SERVER_SSH_KEY}}" > ${HOME}/.ssh/id_rsa
        chmod 700 ${HOME}/.ssh
        chmod 600 ${HOME}/.ssh/*
        eval `ssh-agent -s`
        ssh-add ${HOME}/.ssh/id_rsa

    - name: Deploy to jeremyfelt.com
      run: |
        rsync -chav --delete \
        -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
        --exclude=.git --exclude=.gitignore --exclude=.github --exclude=node_modules --exclude=vendor \
        ./ ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:${{secrets.REMOTE_TARGET}}

    - name: Deploy to happyprime.co
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --exclude=.git --exclude=.gitignore --exclude=.github --exclude=node_modules --exclude=vendor --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_TWO }}
